name: Generate Jar

on:
  push:
    branches:
      - release
      - dev

jobs:
  GeneratrJarFile:
    runs-on: windows-latest
    steps:
      - uses: action/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: run gradle task
        run: ./gradlew.bat copyJar

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: jarFile
          path: ./androidSdk/libs/